# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
future: true
# collections:
#   posts:
#     output: true
#     permalink: /posts/:title

# Blogs labels
title: Blogs de Oportunidades Ilimitadas
description: "Oportunidades Ilimitadas es un sitio web de información especializada en Inteligencia Artificial (IA). Nuestra misión es mantenernos a la vanguardia de las últimas tendencias y desarrollos en el mundo post IA. Ofrecemos información actualizada y relevante en nuestros blogs, además de un directorio web / app completo. Si deseas contribuir, enviarnos un 'leak', e incluso hacer una donación via Paypal en paypal.me/lucfreelance o contactanos."
email: ilimitadasoportunidades@gmail.com
url: "https://oportunidadesilimitadas.com/blogs/_site/index.html"
twitter_username: o_ilimitadas
github_username:  lucfreelance

# Build settings
theme: minima
plugins:
  - jekyll-feed
external_url: https://oportunidadesilimitadas.com/blogs

# Assets folder
assets_dir: /blogs/assets

# Meta tags for SEO
meta_description: "Blogs es un proyecto de Oportunidades Ilimitadas para difundir noticias y bovedades relacionadas con Inteligencia Artificial y Machine Learning. Pásate por aquí cada tanto y encontrarás adelantos, recuentos y hasta predicciones de los extraordinarios avances que día a día la IA impacta al mundo permanentemente. En definitiva la IA vino para quedarse, y en Blogs de Oportunidades Ilimitadas encontrarás mucha información al respecto."
og_description: "Descubre el fascinante mundo de la Inteligencia Artificial y el Machine Learning en Blogs de Oportunidades Ilimitadas. Adelantos, recuentos y predicciones de los extraordinarios avances que están transformando nuestro mundo día a día. La IA vino para quedarse y aquí encontrarás toda la información al respecto."
canonical_url: "https://oportunidadesilimitadas.com/blogs/_site/index.html"
og_url: "https://oportunidadesilimitadas.com/blogs/_site/index.html"
og_site_name: "Blogs de Oportunidades Ilimitadas - Noticias y novedades de IA y Machine Learning"
og_type: "blog"
twitter_card: "summary"
twitter_title: "Blogs x Oportunidades Ilimitadas"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
