# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
future: true
url: "https://oportunidadesilimitadas.com/blogs"
# collections:
#   posts:
#     output: true
#     permalink: /posts/:title

# Blogs labels
title: Blogs de Oportunidades Ilimitadas
excerpt: "Blogs es el feed de Oportunidades Ilimitadas con información actualizada en Inteligencia Artificial General (IAG). Nos mantenemos al frente de las últimas tendencias y desarrollos en la materia. Además te invitamos a explorar el directorio de IAs por categorías más completo en Español table-board. Si deseas contribuir, enviarnos un mensaje, incluso hacer una donación via Paypal, contáctanos WhatsApp de oi_ia"
email: ilimitadasoportunidades@gmail.com
twitter_username: o_ilimitadas
github_username:  lucfreelance

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-time-to-read

# External links
blogs:
  url: "https://oportunidadesilimitadas.com/blogs/_site/index.html"

# Meta tags for SEO
meta_description: "Blogs es un proyecto de Oportunidades Ilimitadas para difundir noticias y novedades relacionadas con Inteligencia Artificial y Machine Learning."
og_description: "Descubre el fascinante mundo de la Inteligencia Artificial y el Machine Learning en Blogs de Oportunidades Ilimitadas. Adelantos, recuentos y predicciones de los extraordinarios avances que están transformando nuestro mundo día a día. La IA vino para quedarse y aquí encontrarás toda la información al respecto."
canonical_url: "{{ site.blogs.url }}"
og_url: "{{ site.blogs.url }}"
og_site_name: "Blogs de Oportunidades Ilimitadas - Noticias y novedades de IA y Machine Learning"
og_type: "blog"
twitter_card: "summary"
twitter_title: "Blogs x Oportunidades Ilimitadas"

# 
defaults:
  -
    scope:
      path: "blogs/*"
    values:
      layout: "blog_layout"
      footer: true
  -
    scope:
      path: ""
    values:
      layout: "default_layout"

# Setup of jekyll-time-to-read
time_to_read: 
words_per_minute: 210 # Promedio estimado de palabras leídas por minuto

# Exclude from processing
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
